# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: "Pierre Pereira"
fullname: "Pierre Pereira"
email: "pierrot-lc.website@proton.me"
description: >- # this means to ignore newlines until "baseurl:"
  Here I discuss about GNNs, RL, NCO and other Deep Learning things.
baseurl: "/website" # the subpath of your site, e.g. /blog
url: "https://pierrot-lc.github.io" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  pierrot-lc

# Build settings
plugins:
  - jekyll-feed

exclude:
  - Gemfile
  - Gemfile.lock
  - Justfile
  - flake.lock
  - flake.nix
  - README.md

themes:
  light:
    text-color: black
  dark:
    text-color: white

defaults:
  - scope:
      path: ""
    values:
      layout: "default"

  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
