compile:
    meson compile -C builddir

setup: clean
    meson setup builddir
    ln -s builddir/compile_commands.json compile_commands.json

clean:
    rm -rf builddir .cache
    rm compile_commands.json
