compile:
    meson compile -C builddir

setup:
    rm -rf builddir
    meson setup builddir
    rm compile_commands.json
    ln -s builddir/compile_commands.json compile_commands.json

clean:
    rm -rf builddir .cache
