---
title: Pierre Pereira's Blog
author: Pierre Pereira
description: >-
  This is my blog and I like it.

home: /index.html
favicon: /favicon.ico

styles:
  - /styles/main.css
  - /styles/katex.min.css
  - /styles/highlight.css

scripts:
  - /scripts/katex.min.js
  - /scripts/highlight.min.js
  - /scripts/renderLatex.js
  - /scripts/renderCode.js
